---
- hosts: all
  tasks:

  - name: Configure DNS
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.33.11   web01
        192.168.33.12   web02
        192.168.33.13   lb01
        
  - name: Install HAProxy Web Server
    package:
      name: haproxy
      state: present

  - name: Deploy HAProxy Configuration
    copy:
      src: haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: 0644

  - name: Ensure HaProxy is enabled and running
    service:
      name: haproxy 
      state: started 
      enabled: yes
